### ISSUE TITLE
$(...).lightGallery is not a function

### ISSUE THREAD

**Issue by getlose** [rjchauhan/RJGallery-for-OctoberCMS#32]
I am using this plugin for my octobercms project and i got this following error
```
Uncaught TypeError: $(...).lightGallery is not a function
    at HTMLDocument.<anonymous> (http://xxx/yyy/index.php/gallery:48:41)
    at c (http://xxx/yyy/plugins/raviraj/rjgallery/assets/js/jquery-1.9.1.min.js:6:9510)
    at Object.fireWith [as resolveWith] (http:xxx/yyy/plugins/raviraj/rjgallery/assets/js/jquery-1.9.1.min.js:6:10529)
    at Function.ready (http:/xxx/yyy/plugins/raviraj/rjgallery/assets/js/jquery-1.9.1.min.js:6:3888)
    at HTMLDocument.H (http://xxx/yyy/plugins/raviraj/rjgallery/assets/js/jquery-1.9.1.min.js:6:796)
gallery:48 
```

any idea why this is happening? thanks

**Comment by rjchauhan** [comment]
try to set `jQuery Inject` option to `Yes`. or try upgrading plugin and check.
